spring:
  application:
    name: algo

  datasource:
    url: jdbc:mysql://localhost:3306/algo
    username: seungjoon
    password: 5150
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 879354679677-ba72gp9a5e2nogv9jshrt5uetrisrpdu.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

  jwt:
    secret: 0509c02230509c02230509c02230509c0223

logging:
  level:
    org.hibernate.SQL: debug